[package]
name = "rocket-demo"
version = "0.1.0"
authors = ["guaifish <guaifish@hotmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
