version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678

volumes:
  mysql:
